# Generated by Django 3.1.6 on 2021-02-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210224_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='expire_date',
            field=models.DateField(null=True),
        ),
    ]
