# Generated by Django 3.1.6 on 2021-03-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210305_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_link',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
